### PR TITLE
chore: add fixes to upstream PR for new source

### PR DESCRIPTION
**Pull request by vincentkoc**
Part of https://github.com/airbytehq/airbyte/pull/16473 adding some additional changes:
* Remove changes outside of the connector
* Re-introduced the catalogue
* Changes from `./gradlew format`
* Attempted to patch the tests

Tests failing
```
         =========================== short test summary info ============================
         FAILED unit_tests/test_incremental_streams.py::test_cursor_field - TypeError:...
         FAILED unit_tests/test_incremental_streams.py::test_get_updated_state - TypeE...
         FAILED unit_tests/test_incremental_streams.py::test_stream_slices - TypeError...
         FAILED unit_tests/test_incremental_streams.py::test_supports_incremental - Ty...
         FAILED unit_tests/test_incremental_streams.py::test_source_defined_cursor - T...
         FAILED unit_tests/test_incremental_streams.py::test_stream_checkpoint_interval
         FAILED unit_tests/test_source.py::test_check_connection - AssertionError: ass...
         FAILED unit_tests/test_streams.py::test_request_params - TypeError: __init__(...
         FAILED unit_tests/test_streams.py::test_next_page_token - TypeError: __init__...
         FAILED unit_tests/test_streams.py::test_parse_response - TypeError: __init__(...
         FAILED unit_tests/test_streams.py::test_request_headers - TypeError: __init__...
         FAILED unit_tests/test_streams.py::test_http_method - TypeError: __init__() m...
         FAILED unit_tests/test_streams.py::test_should_retry[HTTPStatus.OK-False] - T...
         FAILED unit_tests/test_streams.py::test_should_retry[HTTPStatus.BAD_REQUEST-False]
         FAILED unit_tests/test_streams.py::test_should_retry[HTTPStatus.TOO_MANY_REQUESTS-True]
         FAILED unit_tests/test_streams.py::test_should_retry[HTTPStatus.INTERNAL_SERVER_ERROR-True]
         FAILED unit_tests/test_streams.py::test_backoff_time - TypeError: __init__() ...
         ================== 17 failed, 1 passed, 10 warnings in 1.12s ===================
```

### CODE REVIEW

**Comment by robgleason** [comment]
Hello @koconder , I ran the individual scripts in the Unit Test folder, and test_source.py seemed to work when I initialized the environment in the source-weatherstack dir with python -m venv .venv and .venv\scripts\activate . I added the two classes for the Unit Tests for test_incremental and Weatherstackstream. Was there one script you ran to run them all? Let me know if what I did fixed it. Thank you, Robert

**Comment by vincentkoc** [comment]
@robgleason just merge this PR and i can take a look. You need to use gradle to run all the tests

**Comment by robgleason** [comment]
Okay, Awesome. I can resolve any conflict with the two branches and merge them in a few hours.

**Comment by vincentkoc** [comment]
@robgleason ready to merge, i fixed the conflict with your changes

**Pull request merged**
